name: Mineunit runner
description: "Execute unit tests with mineunit & busted"
author: SX / S-S-X
branding:
  icon: file-text
  color: green

inputs:
  working-directory:
    description: "Working directory for unit tests"
    required: true
    default: "."
  luacov-exclude:
    description: "Code coverage exclude patterns"
    required: false
  badge-name:
    description: "Code coverage badge name"
    required: true
    default: "coverage"
  badge-label:
    description: "Code coverage badge label"
    required: true
    default: "Test coverage"
  badge-color:
    description: "Code coverage badge color"
    required: true
    default: "99CC09"
  mineunit-repo:
    description: "Mineunit repository location"
    required: true
    default: "https://github.com/mt-mods/mineunit.git"
  mineunit-directory:
    description: "Mineunit install directory relative to working-directory"
    required: true
    default: "spec/mineunit"

outputs:
  badge-name:
    description: "Code coverage badge name waiting for issues/#1"
    value: ${{ steps.badge-wrapper-actions-issue-1.outputs.badge-name }}
  badge-label:
    description: "Code coverage badge label waiting for issues/#1"
    value: ${{ steps.badge-wrapper-actions-issue-1.outputs.badge-label }}
  badge-status:
    description: "Code coverage badge status waiting for issues/#1"
    value: ${{ steps.badge-wrapper-actions-issue-1.outputs.badge-status }}
  badge-color:
    description: "Code coverage badge color waiting for issues/#1"
    value: ${{ steps.badge-wrapper-actions-issue-1.outputs.badge-color }}
  busted-stdout:
    description: "Stdout produced during busted run"
    value: ${{ steps.busted-run.outputs.busted-stdout }}

runs:
  using: composite
  steps:
    - name: busted install
      shell: bash
      run: |
        sudo apt-get install -y luarocks
        luarocks install --local busted
        luarocks install --local cluacov
    - name: mineunit install
      working-directory: "${{ inputs.working-directory }}"
      shell: bash
      run: |
        [ -f "${{ inputs.mineunit-directory }}/init.lua" ] || git clone --depth 1 "${{ inputs.mineunit-repo }}" "${{ inputs.mineunit-directory }}"
    - name: luacov configuration
      working-directory: "${{ inputs.working-directory }}"
      shell: bash
      run: |
        excludes='${{ inputs.luacov-exclude && format('"{0}"',join(fromJSON(inputs.luacov-exclude),'","')) || '' }}'
        echo 'deletestats=true;includeuntestedfiles=true;exclude={"spec/","/\.?luarocks/","/share/lua/",'"${excludes}"'}'>.luacov
    - id: busted-run
      name: busted run
      working-directory: "${{ inputs.working-directory }}"
      shell: bash
      run: |
        set +eo pipefail
        exec 3>&1
        OUT="$($HOME/.luarocks/bin/busted -c | tee >(cat - >&3); exit ${PIPESTATUS[0]})"
        ERR=$?
        exec 3>&-
        OUT="${OUT//'%'/'%25'}";OUT="${OUT//$'\n'/'%0A'}"
        echo "::set-output name=busted-stdout::${OUT//$'\r'/'%0D'}"
        exit $ERR
    - name: luacov run
      working-directory: "${{ inputs.working-directory }}"
      shell: bash
      run: $HOME/.luarocks/bin/luacov
    - name: collect coverage data
      working-directory: "${{ inputs.working-directory }}"
      shell: bash
      run: |
        (printf coverage=>>$GITHUB_ENV;tail -n 2 luacov.report.out | grep ^Total | grep -o '[0-9.]\+%$'>>$GITHUB_ENV)
        (awk -v p=0 '/^----/{p++;next}p==2{exit}p' luacov.report.out | sort -hrk4 > luacov.report.sum)
        (echo "files=$(grep -cv '\s0\.00%' luacov.report.sum)/$(wc -l<luacov.report.sum)">>$GITHUB_ENV)
    - id: badge-wrapper-actions-issue-1
      name: Input wrapper while waiting for actions in actions feature
      shell: bash
      run: |
        echo "::set-output name=badge-name::${{ inputs.badge-name }}"
        echo "::set-output name=badge-label::${{ inputs.badge-label }}"
        echo "::set-output name=badge-status::${{ env.coverage }} in ${{ env.files }} files"
        echo "::set-output name=badge-color::${{ inputs.badge-color }}"
